[manifest]
version = "0.1.0"
dump_lua = true
priority = 0

# Challenges

# Change challenge colors


[[patches]]
[patches.regex]
target = "functions/UI_definitions.lua"
pattern = '''UIBox_button\(\{id = k.*'''
position = 'at'
match_indent = true
payload = '''
UIBox_button({id = k, col = true, label = {challenge_unlocked and localize(v.id, 'challenge_names') or localize('k_locked'),}, button = challenge_unlocked and 'change_challenge_description' or 'nil', colour = challenge_unlocked and (JoyousSpring and JoyousSpring.get_challenge_colour(v) or G.C.RED) or G.C.GREY, minw = 4, scale = 0.4, minh = 0.6, focus_args = {snap_to = not snapped}}),
'''

[[patches]]
[patches.regex]
target = "game.lua"
pattern = "if v.pinned then _joker.pinned = true end"
position = 'after'
match_indent = true
payload = '''
if v.joy_summoned then 
    if JoyousSpring.is_monster_card(_joker) then
        _joker.ability.extra.joyous_spring.summoned = true
    end
end
if v.joy_revived then 
    if JoyousSpring.is_monster_card(_joker) then
        _joker.ability.extra.joyous_spring.revived = true
    end
end
'''


          