[manifest]
version = "0.1.0"
dump_lua = true
priority = 0

# Challenges

# Custom rules
[[patches]]
[patches.pattern]
target = "game.lua"
pattern = "if v.pinned then _joker.pinned = true end"
position = 'after'
match_indent = true
payload = '''
if v.joy_summoned then
    if JoyousSpring.is_monster_card(_joker) then
        _joker.ability.extra.joyous_spring.summoned = true
    end
end
if v.joy_revived then
    if JoyousSpring.is_monster_card(_joker) then
        _joker.ability.extra.joyous_spring.revived = true
    end
end
'''
