[manifest]
version = "0.1.0"
dump_lua = true
priority = 0

# Add Hanafuda enhancements to poker hand screen
[[patches]]
[patches.pattern]
target = "functions/UI_definitions.lua"
pattern = '''local card = Card(0,0, 0.5*G.CARD_W, 0.5*G.CARD_H, G.P_CARDS[v[1]], G.P_CENTERS[v.enhancement or 'c_base'])'''
position = "after"
payload = '''
if v.joy_hanafuda then
    G.E_MANAGER:add_event(Event({
        blockable = false,
        func = (function()
            card.children.center:set_sprite_pos(JoyousSpring.hanafuda_cards[v.joy_hanafuda].pos)
            return true
        end)
    }))
end
'''
match_indent = true
